/* Generated by Yosys 0.60+95 (git sha1 991e70489, clang++ 18.1.8 -fPIC -O3) */

module compteur_Barch_compteur(clk, reset, ce, raz, count);
  input clk;
  wire clk;
  input reset;
  wire reset;
  input ce;
  wire ce;
  input raz;
  wire raz;
  output [7:0] count;
  wire [7:0] count;
  wire _0_;
  wire [7:0] _1_;
  wire [7:0] _2_;
  wire [7:0] _3_;
  wire [7:0] _4_;
  wire _5_;
  reg [7:0] count_int;
  always @(posedge clk, posedge reset)
    if (reset) count_int <= 8'h00;
    else if (_5_) count_int <= _4_;
  assign _5_ = | { ce, raz };
  assign _0_ = count_int == 8'h63;
  assign _1_ = count_int + 8'h01;
  assign _2_ = _0_ ? 8'h00 : _1_;
  assign _3_ = ce ? _2_ : 8'hxx;
  assign _4_ = raz ? 8'h00 : _3_;
  assign count = count_int;
endmodule

module count_split_Barch_count_split(din, msb_nibble, lsb_nibble);
  input [7:0] din;
  wire [7:0] din;
  output [3:0] msb_nibble;
  wire [3:0] msb_nibble;
  output [3:0] lsb_nibble;
  wire [3:0] lsb_nibble;
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30" *)
  wire [30:0] _0_;
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30" *)
  wire [30:0] _1_;
  (* unused_bits = "4 5 6 7" *)
  wire [7:0] result;
  (* unused_bits = "4 5 6 7" *)
  wire [7:0] result2;
  assign { _0_[30:8], result[7:4], msb_nibble } = { 23'h000000, din } / 31'h0000000a;
  assign { _1_[30:8], result2[7:4], lsb_nibble } = { 23'h000000, din } % 31'h0000000a;
  assign _0_[7:0] = { result[7:4], msb_nibble };
  assign _1_[7:0] = { result2[7:4], lsb_nibble };
  assign result[3:0] = msb_nibble;
  assign result2[3:0] = lsb_nibble;
endmodule

module dec_sev_seg_Barch_dec_sev_seg(din, dout);
  input [3:0] din;
  wire [3:0] din;
  output [6:0] dout;
  wire [6:0] dout;
  wire _00_;
  wire _01_;
  wire [6:0] _02_;
  wire _03_;
  wire [6:0] _04_;
  wire _05_;
  wire [6:0] _06_;
  wire _07_;
  wire [6:0] _08_;
  wire _09_;
  wire [6:0] _10_;
  wire _11_;
  wire [6:0] _12_;
  wire _13_;
  wire [6:0] _14_;
  wire _15_;
  wire [6:0] _16_;
  wire _17_;
  wire [6:0] _18_;
  wire _19_;
  wire [6:0] _20_;
  wire _21_;
  wire [6:0] _22_;
  wire _23_;
  wire [6:0] _24_;
  wire _25_;
  wire [6:0] _26_;
  wire _27_;
  wire [6:0] _28_;
  wire _29_;
  wire [6:0] _30_;
  wire [6:0] conv;
  assign _11_ = din == 4'h6;
  assign _12_ = _11_ ? 7'h7d : _14_;
  assign _13_ = din == 4'h7;
  assign _14_ = _13_ ? 7'h07 : _16_;
  assign _15_ = din == 4'h8;
  assign _16_ = _15_ ? 7'h7f : _18_;
  assign _17_ = din == 4'h9;
  assign _18_ = _17_ ? 7'h6f : _20_;
  assign _19_ = din == 4'ha;
  assign _20_ = _19_ ? 7'h77 : _22_;
  assign _21_ = din == 4'hb;
  assign _22_ = _21_ ? 7'h7c : _24_;
  assign _23_ = din == 4'hc;
  assign _24_ = _23_ ? 7'h39 : _26_;
  assign _25_ = din == 4'hd;
  assign _26_ = _25_ ? 7'h5e : _28_;
  assign _27_ = din == 4'he;
  assign _28_ = _27_ ? 7'h79 : _30_;
  assign _29_ = din == 4'hf;
  assign _30_ = _29_ ? 7'h71 : 7'h00;
  assign dout = ~ conv;
  assign _00_ = ! din;
  assign conv = _00_ ? 7'h3f : _02_;
  assign _01_ = din == 4'h1;
  assign _02_ = _01_ ? 7'h06 : _04_;
  assign _03_ = din == 4'h2;
  assign _04_ = _03_ ? 7'h5b : _06_;
  assign _05_ = din == 4'h3;
  assign _06_ = _05_ ? 7'h4f : _08_;
  assign _07_ = din == 4'h4;
  assign _08_ = _07_ ? 7'h66 : _10_;
  assign _09_ = din == 4'h5;
  assign _10_ = _09_ ? 7'h6d : _12_;
endmodule

module div_freq_1s_Barch_div_freq_1s(clk, reset, fs, fs_sym);
  input clk;
  wire clk;
  input reset;
  wire reset;
  output fs;
  wire fs;
  output fs_sym;
  wire fs_sym;
  wire _0_;
  wire [23:0] _1_;
  wire [23:0] _2_;
  wire _3_;
  reg [23:0] count_int;
  assign _0_ = count_int == 24'hb71aff;
  assign _1_ = count_int + 24'h000001;
  assign _2_ = _0_ ? 24'h000000 : _1_;
  assign _3_ = count_int < 24'h5b8d80;
  assign fs_sym = _3_ ? 1'h1 : 1'h0;
  always @(posedge clk, posedge reset)
    if (reset) count_int <= 24'h000000;
    else count_int <= _2_;
  assign fs = count_int[23];
endmodule

module div_freq_255_Barch_div_freq_255(clk, reset, fs_sym);
  input clk;
  wire clk;
  input reset;
  wire reset;
  output fs_sym;
  wire fs_sym;
  wire _0_;
  wire [23:0] _1_;
  wire [23:0] _2_;
  wire _3_;
  reg [23:0] count_int;
  assign _0_ = count_int == 24'h00b797;
  assign _1_ = count_int + 24'h000001;
  assign _2_ = _0_ ? 24'h000000 : _1_;
  assign _3_ = count_int < 24'h005bcc;
  assign fs_sym = _3_ ? 1'h1 : 1'h0;
  always @(posedge clk, posedge reset)
    if (reset) count_int <= 24'h000000;
    else count_int <= _2_;
endmodule

module icebreaker(CLK, BTN_N, BTN1, BTN2, BTN3, LED1, LED2, LED3, LED4, P1A1, P1A2, P1A3, P1A4, P1A7, P1A8, P1A9, P1A10);
  input CLK;
  wire CLK;
  input BTN_N;
  wire BTN_N;
  input BTN1;
  wire BTN1;
  input BTN2;
  wire BTN2;
  input BTN3;
  wire BTN3;
  output LED1;
  wire LED1;
  output LED2;
  wire LED2;
  output LED3;
  wire LED3;
  output LED4;
  wire LED4;
  output P1A1;
  wire P1A1;
  output P1A2;
  wire P1A2;
  output P1A3;
  wire P1A3;
  output P1A4;
  wire P1A4;
  output P1A7;
  wire P1A7;
  output P1A8;
  wire P1A8;
  output P1A9;
  wire P1A9;
  output P1A10;
  wire P1A10;
  wire ce;
  wire clk_count;
  wire [7:0] count;
  wire fs_255s;
  wire [3:0] lsb_nibble;
  wire [3:0] msb_nibble;
  wire [3:0] nibble;
  wire raz;
  wire reset;
  wire [6:0] sev_seg;
  assign reset = ~ BTN_N;
  compteur_Barch_compteur compteur0 (
    .ce(ce),
    .clk(clk_count),
    .count(count),
    .raz(raz),
    .reset(reset)
  );
  count_split_Barch_count_split count_split0 (
    .din(count),
    .lsb_nibble(lsb_nibble),
    .msb_nibble(msb_nibble)
  );
  dec_sev_seg_Barch_dec_sev_seg dec_sev_seg0 (
    .din(nibble),
    .dout(sev_seg)
  );
  div_freq_1s_Barch_div_freq_1s div_freq0 (
    .clk(CLK),
    .fs(clk_count),
    .fs_sym(LED1),
    .reset(reset)
  );
  div_freq_255_Barch_div_freq_255 div_freq1 (
    .clk(CLK),
    .fs_sym(fs_255s),
    .reset(reset)
  );
  mux_Barch_mux mux0 (
    .e0(msb_nibble),
    .e1(lsb_nibble),
    .s(nibble),
    .sel(fs_255s)
  );
  state_machine_Barch_state_machine state_machine0 (
    .btn_init(BTN1),
    .btn_pause(BTN3),
    .btn_run(BTN2),
    .cen(ce),
    .clk(CLK),
    .led_i(LED2),
    .led_p(LED4),
    .led_r(LED3),
    .raz(raz),
    .reset(reset)
  );
  assign P1A1 = sev_seg[0];
  assign P1A10 = fs_255s;
  assign P1A2 = sev_seg[1];
  assign P1A3 = sev_seg[2];
  assign P1A4 = sev_seg[3];
  assign P1A7 = sev_seg[4];
  assign P1A8 = sev_seg[5];
  assign P1A9 = sev_seg[6];
endmodule

module mux_Barch_mux(e0, e1, sel, s);
  input [3:0] e0;
  wire [3:0] e0;
  input [3:0] e1;
  wire [3:0] e1;
  input sel;
  wire sel;
  output [3:0] s;
  wire [3:0] s;
  assign s = sel ? e1 : e0;
endmodule

module state_machine_Barch_state_machine(reset, clk, btn_init, btn_run, btn_pause, raz, cen, led_i, led_r, led_p);
  input reset;
  wire reset;
  input clk;
  wire clk;
  input btn_init;
  wire btn_init;
  input btn_run;
  wire btn_run;
  input btn_pause;
  wire btn_pause;
  output raz;
  wire raz;
  output cen;
  wire cen;
  output led_i;
  wire led_i;
  output led_r;
  wire led_r;
  output led_p;
  wire led_p;
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire [1:0] _04_;
  wire [1:0] _05_;
  wire _06_;
  wire _07_;
  wire [1:0] _08_;
  wire [1:0] _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  reg [1:0] etat_cr;
  wire [1:0] etat_sv;
  always @(posedge clk, posedge reset)
    if (reset) etat_cr <= 2'h0;
    else if (_14_) etat_cr <= etat_sv;
  assign _11_ = { btn_init, _07_, _10_ } != 3'h1;
  assign _12_ = { btn_init, _03_, _06_ } != 3'h1;
  assign _13_ = { btn_run, _01_ } != 2'h1;
  assign _14_ = & { _11_, _12_, _13_ };
  assign _15_ = | { _01_, _06_ };
  assign _16_ = | { _01_, _10_ };
  assign _17_ = | { _06_, _10_ };
  assign _00_ = btn_run ? 2'h1 : 2'hx;
  assign _01_ = ! etat_cr;
  assign _03_ = _02_ & btn_pause;
  assign _04_ = _03_ ? 2'h2 : 2'hx;
  assign _05_ = btn_init ? 2'h0 : _04_;
  assign _06_ = etat_cr == 2'h1;
  assign _02_ = ~ btn_init;
  assign _07_ = _02_ & btn_run;
  assign _08_ = _07_ ? 2'h1 : 2'hx;
  assign _09_ = btn_init ? 2'h0 : _08_;
  assign _10_ = etat_cr == 2'h2;
  function [0:0] \:190 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \:190  = b[0:0];
      2'b1?:
        \:190  = b[1:1];
      default:
        \:190  = a;
    endcase
  endfunction
  assign led_i = \:190 (1'hx, 2'h1, { _17_, _01_ });
  function [0:0] \:195 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \:195  = b[0:0];
      2'b1?:
        \:195  = b[1:1];
      default:
        \:195  = a;
    endcase
  endfunction
  assign cen = \:195 (1'hx, 2'h2, { _06_, _16_ });
  function [0:0] \:200 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \:200  = b[0:0];
      2'b1?:
        \:200  = b[1:1];
      default:
        \:200  = a;
    endcase
  endfunction
  assign led_p = \:200 (1'hx, 2'h2, { _10_, _15_ });
  function [1:0] \:203 ;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:203  = b[1:0];
      3'b?1?:
        \:203  = b[3:2];
      3'b1??:
        \:203  = b[5:4];
      default:
        \:203  = a;
    endcase
  endfunction
  assign etat_sv = \:203 (2'hx, { _09_, _05_, _00_ }, { _10_, _06_, _01_ });
  assign led_r = cen;
  assign raz = led_i;
endmodule
