/* Generated by Yosys 0.60+95 (git sha1 991e70489, clang++ 18.1.8 -fPIC -O3) */

module compteur_2b_Barch_compteur_2b(clk, ce, raz, count);
  input clk;
  wire clk;
  input ce;
  wire ce;
  input raz;
  wire raz;
  output [1:0] count;
  wire [1:0] count;
  wire _0_;
  wire [1:0] _1_;
  wire [1:0] _2_;
  wire [1:0] _3_;
  reg [1:0] count_int;
  always @(posedge clk)
    if (raz) count_int <= 2'h0;
    else if (ce) count_int <= _3_;
  assign _0_ = count_int == 2'h3;
  assign _1_ = count_int + 2'h1;
  assign _2_ = _0_ ? 2'h0 : _1_;
  assign _3_ = ce ? _2_ : 2'hx;
  assign count = count_int;
endmodule

module compteur_baudrate_Barch_compteur_baudrate(clk, ce, raz, count);
  input clk;
  wire clk;
  input ce;
  wire ce;
  input raz;
  wire raz;
  output [7:0] count;
  wire [7:0] count;
  wire _0_;
  wire [7:0] _1_;
  wire [7:0] _2_;
  wire [7:0] _3_;
  reg [7:0] count_int;
  always @(posedge clk)
    if (raz) count_int <= 8'h00;
    else if (ce) count_int <= _3_;
  assign _0_ = count_int == 8'h33;
  assign _1_ = count_int + 8'h01;
  assign _2_ = _0_ ? 8'h00 : _1_;
  assign _3_ = ce ? _2_ : 8'hxx;
  assign count = count_int;
endmodule

module compteur_nb_bits_Barch_compteur_nb_bits(clk, ce, raz, count);
  input clk;
  wire clk;
  input ce;
  wire ce;
  input raz;
  wire raz;
  output [7:0] count;
  wire [7:0] count;
  wire _0_;
  wire [7:0] _1_;
  wire [7:0] _2_;
  wire [7:0] _3_;
  reg [7:0] count_int;
  always @(posedge clk)
    if (raz) count_int <= 8'h00;
    else if (ce) count_int <= _3_;
  assign _0_ = count_int == 8'h0a;
  assign _1_ = count_int + 8'h01;
  assign _2_ = _0_ ? 8'h00 : _1_;
  assign _3_ = ce ? _2_ : 8'hxx;
  assign count = count_int;
endmodule

module fsm_icebreaker_Barch_fsm_icebreaker(clk, reset, init, load, send, ready, start, ce, raz_count, ld_t);
  input clk;
  wire clk;
  input reset;
  wire reset;
  input init;
  wire init;
  input load;
  wire load;
  input send;
  wire send;
  input ready;
  wire ready;
  output start;
  wire start;
  output ce;
  wire ce;
  output raz_count;
  wire raz_count;
  output ld_t;
  wire ld_t;
  wire _00_;
  wire [2:0] _01_;
  wire _02_;
  wire _03_;
  wire [2:0] _04_;
  wire [2:0] _05_;
  wire _06_;
  wire _07_;
  wire [2:0] _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  reg [2:0] etat_cr;
  wire [2:0] etat_sv;
  always @(posedge clk, posedge reset)
    if (reset) etat_cr <= 3'h0;
    else if (_13_) etat_cr <= etat_sv;
  assign _10_ = { ready, _09_ } != 2'h1;
  assign _11_ = { send, init, _06_ } != 3'h1;
  assign _12_ = { load, _02_ } != 2'h1;
  assign _13_ = & { _10_, _11_, _12_ };
  assign _15_ = | { _02_, _03_, _06_, _07_, _09_ };
  assign _14_ = | { _00_, _02_, _06_, _07_, _09_ };
  assign _16_ = | { _00_, _02_, _03_, _06_, _09_ };
  function [2:0] \:103 ;
    input [2:0] a;
    input [17:0] b;
    input [5:0] s;
    (* parallel_case *)
    casez (s)
      6'b?????1:
        \:103  = b[2:0];
      6'b????1?:
        \:103  = b[5:3];
      6'b???1??:
        \:103  = b[8:6];
      6'b??1???:
        \:103  = b[11:9];
      6'b?1????:
        \:103  = b[14:12];
      6'b1?????:
        \:103  = b[17:15];
      default:
        \:103  = a;
    endcase
  endfunction
  assign etat_sv = \:103 (3'hx, { _08_, 3'h5, _05_, 3'h3, _01_, 3'h1 }, { _09_, _07_, _06_, _03_, _02_, _00_ });
  assign _00_ = ! etat_cr;
  assign _01_ = load ? 3'h2 : 3'hx;
  assign _02_ = etat_cr == 3'h1;
  assign _03_ = etat_cr == 3'h2;
  assign _04_ = send ? 3'h4 : 3'hx;
  assign _05_ = init ? 3'h1 : _04_;
  assign _06_ = etat_cr == 3'h3;
  assign _07_ = etat_cr == 3'h4;
  assign _08_ = ready ? 3'h1 : 3'hx;
  assign _09_ = etat_cr == 3'h5;
  function [0:0] \:82 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \:82  = b[0:0];
      2'b1?:
        \:82  = b[1:1];
      default:
        \:82  = a;
    endcase
  endfunction
  assign start = \:82 (1'hx, 2'h2, { _07_, _16_ });
  function [0:0] \:92 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \:92  = b[0:0];
      2'b1?:
        \:92  = b[1:1];
      default:
        \:92  = a;
    endcase
  endfunction
  assign raz_count = \:92 (1'hx, 2'h1, { _15_, _00_ });
  function [0:0] \:97 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \:97  = b[0:0];
      2'b1?:
        \:97  = b[1:1];
      default:
        \:97  = a;
    endcase
  endfunction
  assign ce = \:97 (1'hx, 2'h2, { _03_, _14_ });
  assign ld_t = ce;
endmodule

module fsm_serial_Barch_fsm_serial(clk, reset, start, count_baudrate, count_nb_bits, ce_baudrate, raz_baudrate, ce_nb_bits, raz_nb_bits, ready, raz_ser, id_ser, ser);
  input clk;
  wire clk;
  input reset;
  wire reset;
  input start;
  wire start;
  input [7:0] count_baudrate;
  wire [7:0] count_baudrate;
  input [7:0] count_nb_bits;
  wire [7:0] count_nb_bits;
  output ce_baudrate;
  wire ce_baudrate;
  output raz_baudrate;
  wire raz_baudrate;
  output ce_nb_bits;
  wire ce_nb_bits;
  output raz_nb_bits;
  wire raz_nb_bits;
  output ready;
  wire ready;
  output raz_ser;
  wire raz_ser;
  output id_ser;
  wire id_ser;
  output ser;
  wire ser;
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire [1:0] _05_;
  wire [1:0] _06_;
  wire _07_;
  wire _08_;
  wire [1:0] _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  reg [1:0] etat_cr;
  wire [1:0] etat_sv;
  always @(posedge clk, posedge reset)
    if (reset) etat_cr <= 2'h0;
    else if (_14_) etat_cr <= etat_sv;
  assign _11_ = { _08_, _10_ } != 2'h1;
  assign _12_ = { _03_, _04_, _07_ } != 3'h1;
  assign _13_ = { start, _01_ } != 2'h1;
  assign _14_ = & { _11_, _12_, _13_ };
  assign _16_ = | { _01_, _02_, _10_ };
  assign _17_ = | { _01_, _02_, _07_ };
  assign _18_ = | { _01_, _07_, _10_ };
  assign _15_ = | { _02_, _07_, _10_ };
  assign _00_ = start ? 2'h1 : 2'hx;
  assign _01_ = ! etat_cr;
  assign _02_ = etat_cr == 2'h1;
  assign _03_ = count_nb_bits < 8'h0a;
  assign _04_ = count_nb_bits == 8'h0a;
  assign _05_ = _04_ ? 2'h0 : 2'hx;
  assign _06_ = _03_ ? 2'h3 : _05_;
  assign _07_ = etat_cr == 2'h2;
  assign _08_ = count_baudrate == 8'h33;
  assign _09_ = _08_ ? 2'h2 : 2'hx;
  assign _10_ = etat_cr == 2'h3;
  function [0:0] \:202 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \:202  = b[0:0];
      2'b1?:
        \:202  = b[1:1];
      default:
        \:202  = a;
    endcase
  endfunction
  assign ce_baudrate = \:202 (1'hx, 2'h2, { _10_, _17_ });
  function [0:0] \:227 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \:227  = b[0:0];
      2'b1?:
        \:227  = b[1:1];
      default:
        \:227  = a;
    endcase
  endfunction
  assign raz_nb_bits = \:227 (1'hx, 2'h1, { _15_, _01_ });
  function [0:0] \:232 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \:232  = b[0:0];
      2'b1?:
        \:232  = b[1:1];
      default:
        \:232  = a;
    endcase
  endfunction
  assign id_ser = \:232 (1'hx, 2'h2, { _02_, _18_ });
  function [0:0] \:237 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \:237  = b[0:0];
      2'b1?:
        \:237  = b[1:1];
      default:
        \:237  = a;
    endcase
  endfunction
  assign ce_nb_bits = \:237 (1'hx, 2'h2, { _07_, _16_ });
  function [1:0] \:241 ;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \:241  = b[1:0];
      4'b??1?:
        \:241  = b[3:2];
      4'b?1??:
        \:241  = b[5:4];
      4'b1???:
        \:241  = b[7:6];
      default:
        \:241  = a;
    endcase
  endfunction
  assign etat_sv = \:241 (2'hx, { _09_, _06_, 2'h2, _00_ }, { _10_, _07_, _02_, _01_ });
  assign raz_baudrate = ce_nb_bits;
  assign raz_ser = raz_nb_bits;
  assign ready = raz_nb_bits;
  assign ser = ce_nb_bits;
endmodule

module icebreaker(CLK, BTN_N, BTN1, BTN2, BTN3, TX, LED_RED_N);
  input CLK;
  wire CLK;
  input BTN_N;
  wire BTN_N;
  input BTN1;
  wire BTN1;
  input BTN2;
  wire BTN2;
  input BTN3;
  wire BTN3;
  output TX;
  wire TX;
  output LED_RED_N;
  wire LED_RED_N;
  wire ce;
  wire [1:0] comptage;
  wire [7:0] data_to_send;
  wire ld_t;
  wire raz_count;
  wire ready;
  wire reset;
  wire start;
  assign reset = ~ BTN_N;
  compteur_2b_Barch_compteur_2b compteur_2b_0 (
    .ce(ce),
    .clk(CLK),
    .count(comptage),
    .raz(raz_count)
  );
  fsm_icebreaker_Barch_fsm_icebreaker fsm_icebreaker0 (
    .ce(ce),
    .clk(CLK),
    .init(BTN1),
    .ld_t(ld_t),
    .load(BTN2),
    .raz_count(raz_count),
    .ready(ready),
    .reset(reset),
    .send(BTN3),
    .start(start)
  );
  rom_Barch_rom_2 rom0 (
    .addr(comptage),
    .data(data_to_send)
  );
  uart_Barch_uart uart0 (
    .clk(CLK),
    .data_to_send(data_to_send),
    .ld_t(ld_t),
    .ready(ready),
    .reset(reset),
    .start(start),
    .tx(TX),
    .tx_test(LED_RED_N)
  );
endmodule

module reg_serial_Barch_reg_serial(rotate, load, raz, clk, d_in, tx, tx_test);
  input rotate;
  wire rotate;
  input load;
  wire load;
  input raz;
  wire raz;
  input clk;
  wire clk;
  input [7:0] d_in;
  wire [7:0] d_in;
  output tx;
  wire tx;
  output tx_test;
  wire tx_test;
  wire [9:0] _0_;
  (* unused_bits = "0 1" *)
  wire [9:0] _1_;
  wire [9:0] _2_;
  wire _3_;
  wire _4_;
  wire [9:0] register_serial;
  reg [1:0] _5_;
  always @(posedge clk)
    if (_4_) _5_ <= 2'h1;
    else if (rotate) _5_ <= _0_[1:0];
  assign { register_serial[1], tx } = _5_;
  reg [7:0] _6_;
  always @(posedge clk)
    if (raz) _6_ <= 8'h00;
    else if (_3_) _6_ <= _1_[9:2];
  assign register_serial[9:2] = _6_;
  assign _3_ = | { rotate, load };
  assign _4_ = | { load, raz };
  assign _0_ = rotate ? _2_ : 10'hxxx;
  assign _1_ = load ? { d_in, 2'h1 } : _0_;
  assign _2_ = { 1'h0, register_serial[9:1] } | { tx, 9'h000 };
  assign register_serial[0] = tx;
  assign tx_test = tx;
endmodule

module reg_tampon_Barch_reg_tampon(load, reset, clk, d_in, d_out);
  input load;
  wire load;
  input reset;
  wire reset;
  input clk;
  wire clk;
  input [7:0] d_in;
  wire [7:0] d_in;
  output [7:0] d_out;
  reg [7:0] d_out;
  always @(posedge clk, posedge reset)
    if (reset) d_out <= 8'h00;
    else if (load) d_out <= d_in;
endmodule

module rom_Barch_rom_2(addr, data);
  input [1:0] addr;
  wire [1:0] addr;
  output [7:0] data;
  wire [7:0] data;
  wire [2:0] _0_;
  wire [2:0] _1_;
  assign data[2:0] = addr[1] ? _1_ : _0_;
  assign _0_ = addr[0] ? 3'h2 : 3'h1;
  assign _1_ = addr[0] ? 3'h4 : 3'h3;
  assign data[7:3] = 5'h0c;
endmodule

module uart_Barch_uart(clk, reset, start, ld_t, data_to_send, ready, tx, tx_test);
  input clk;
  wire clk;
  input reset;
  wire reset;
  input start;
  wire start;
  input ld_t;
  wire ld_t;
  input [7:0] data_to_send;
  wire [7:0] data_to_send;
  output ready;
  wire ready;
  output tx;
  wire tx;
  output tx_test;
  wire tx_test;
  wire ce_baudrate;
  wire ce_nb_bits;
  wire [7:0] count_baudrate;
  wire [7:0] count_nb_bits;
  wire id_ser;
  wire raz_baudrate;
  wire raz_nb_bits;
  wire raz_ser;
  wire ser;
  wire [7:0] tamp_out;
  compteur_baudrate_Barch_compteur_baudrate compteur_baudrate0 (
    .ce(ce_baudrate),
    .clk(clk),
    .count(count_baudrate),
    .raz(raz_baudrate)
  );
  compteur_nb_bits_Barch_compteur_nb_bits compteur_nb_bits0 (
    .ce(ce_nb_bits),
    .clk(clk),
    .count(count_nb_bits),
    .raz(raz_nb_bits)
  );
  fsm_serial_Barch_fsm_serial fsm_serial0 (
    .ce_baudrate(ce_baudrate),
    .ce_nb_bits(ce_nb_bits),
    .clk(clk),
    .count_baudrate(count_baudrate),
    .count_nb_bits(count_nb_bits),
    .id_ser(id_ser),
    .raz_baudrate(raz_baudrate),
    .raz_nb_bits(raz_nb_bits),
    .raz_ser(raz_ser),
    .ready(ready),
    .reset(reset),
    .ser(ser),
    .start(start)
  );
  reg_serial_Barch_reg_serial reg_serial0 (
    .clk(clk),
    .d_in(tamp_out),
    .load(id_ser),
    .raz(raz_ser),
    .rotate(ser),
    .tx(tx),
    .tx_test(tx_test)
  );
  reg_tampon_Barch_reg_tampon reg_tampon0 (
    .clk(clk),
    .d_in(data_to_send),
    .d_out(tamp_out),
    .load(ld_t),
    .reset(reset)
  );
endmodule
