/* Generated by Yosys 0.60+95 (git sha1 991e70489, clang++ 18.1.8 -fPIC -O3) */

module compteur_2b_Barch_compteur_2b(clk, raz, ce, count);
  input clk;
  wire clk;
  input raz;
  wire raz;
  input ce;
  wire ce;
  output [1:0] count;
  wire [1:0] count;
  wire _0_;
  wire [1:0] _1_;
  wire [1:0] _2_;
  wire [1:0] _3_;
  reg [1:0] count_int;
  always @(posedge clk)
    if (raz) count_int <= 2'h0;
    else if (ce) count_int <= _3_;
  assign _0_ = count_int == 2'h3;
  assign _1_ = count_int + 2'h1;
  assign _2_ = _0_ ? 2'h0 : _1_;
  assign _3_ = ce ? _2_ : 2'hx;
  assign count = count_int;
endmodule

module compteur_baudrate_Barch_compteur_baudrate(clk, raz, ce, count);
  input clk;
  wire clk;
  input raz;
  wire raz;
  input ce;
  wire ce;
  output [7:0] count;
  wire [7:0] count;
  wire _0_;
  wire [7:0] _1_;
  wire [7:0] _2_;
  wire [7:0] _3_;
  reg [7:0] count_int;
  always @(posedge clk)
    if (raz) count_int <= 8'h00;
    else if (ce) count_int <= _3_;
  assign _0_ = count_int == 8'hff;
  assign _1_ = count_int + 8'h01;
  assign _2_ = _0_ ? 8'h00 : _1_;
  assign _3_ = ce ? _2_ : 8'hxx;
  assign count = count_int;
endmodule

module compteur_nb_bits_Barch_compteur_nb_bits(clk, raz, ce, count);
  input clk;
  wire clk;
  input raz;
  wire raz;
  input ce;
  wire ce;
  output [3:0] count;
  wire [3:0] count;
  wire _0_;
  wire [3:0] _1_;
  wire [3:0] _2_;
  wire [3:0] _3_;
  reg [3:0] count_int;
  always @(posedge clk)
    if (raz) count_int <= 4'h0;
    else if (ce) count_int <= _3_;
  assign _0_ = count_int == 4'hf;
  assign _1_ = count_int + 4'h1;
  assign _2_ = _0_ ? 4'h0 : _1_;
  assign _3_ = ce ? _2_ : 4'hx;
  assign count = count_int;
endmodule

module div_freq_Barch_div_freq(clk, reset, fs);
  input clk;
  wire clk;
  input reset;
  wire reset;
  output fs;
  wire fs;
  wire _0_;
  wire [23:0] _1_;
  wire [23:0] _2_;
  wire _3_;
  reg [23:0] count_int;
  assign _3_ = ! count_int;
  assign fs = _3_ ? 1'h1 : 1'h0;
  always @(posedge clk, posedge reset)
    if (reset) count_int <= 24'h000000;
    else count_int <= _2_;
  assign _0_ = count_int == 24'h000068;
  assign _1_ = count_int + 24'h000001;
  assign _2_ = _0_ ? 24'h000000 : _1_;
endmodule

module fsm_icebreaker_Barch_fsm_icebreaker(clk, reset, init, load, send, ready, start, ld_t, ce, raz_count);
  input clk;
  wire clk;
  input reset;
  wire reset;
  input init;
  wire init;
  input load;
  wire load;
  input send;
  wire send;
  input ready;
  wire ready;
  output start;
  wire start;
  output ld_t;
  wire ld_t;
  output ce;
  wire ce;
  output raz_count;
  wire raz_count;
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire [1:0] _03_;
  wire _04_;
  wire [1:0] _05_;
  wire [1:0] _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  reg [1:0] etat_cr;
  wire [1:0] etat_sv;
  always @(posedge clk, posedge reset)
    if (reset) etat_cr <= 2'h0;
    else if (_11_) etat_cr <= etat_sv;
  assign _08_ = { ready, init, _07_ } != 3'h1;
  assign _09_ = { send, _04_ } != 2'h1;
  assign _10_ = { load, _01_ } != 2'h1;
  assign _11_ = & { _08_, _09_, _10_ };
  assign _12_ = | { _01_, _04_, _07_ };
  assign _13_ = | { _01_, _02_, _04_ };
  assign _00_ = load ? 2'h1 : 2'hx;
  assign _01_ = ! etat_cr;
  assign _02_ = etat_cr == 2'h1;
  assign _03_ = send ? 2'h3 : 2'hx;
  assign _04_ = etat_cr == 2'h2;
  assign _05_ = ready ? 2'h0 : 2'hx;
  assign _06_ = init ? 2'h0 : _05_;
  assign _07_ = etat_cr == 2'h3;
  function [0:0] \:70 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \:70  = b[0:0];
      2'b1?:
        \:70  = b[1:1];
      default:
        \:70  = a;
    endcase
  endfunction
  assign start = \:70 (1'hx, 2'h2, { _07_, _13_ });
  function [0:0] \:80 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \:80  = b[0:0];
      2'b1?:
        \:80  = b[1:1];
      default:
        \:80  = a;
    endcase
  endfunction
  assign ce = \:80 (1'hx, 2'h2, { _02_, _12_ });
  function [1:0] \:84 ;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \:84  = b[1:0];
      4'b??1?:
        \:84  = b[3:2];
      4'b?1??:
        \:84  = b[5:4];
      4'b1???:
        \:84  = b[7:6];
      default:
        \:84  = a;
    endcase
  endfunction
  assign etat_sv = \:84 (2'hx, { _06_, _03_, 2'h2, _00_ }, { _07_, _04_, _02_, _01_ });
  assign ld_t = ce;
  assign raz_count = 1'h0;
endmodule

module fsm_serial_Barch_fsm_serial(clk, reset, start, count_nb_bits, count_baudrate, raz_ser, ld_ser, ser, raz_count_nb_bits, ce_count_nb_bits, raz_count_baudrate, ce_count_baudrate, ready);
  input clk;
  wire clk;
  input reset;
  wire reset;
  input start;
  wire start;
  input [3:0] count_nb_bits;
  wire [3:0] count_nb_bits;
  input [7:0] count_baudrate;
  wire [7:0] count_baudrate;
  output raz_ser;
  wire raz_ser;
  output ld_ser;
  wire ld_ser;
  output ser;
  wire ser;
  output raz_count_nb_bits;
  wire raz_count_nb_bits;
  output ce_count_nb_bits;
  wire ce_count_nb_bits;
  output raz_count_baudrate;
  wire raz_count_baudrate;
  output ce_count_baudrate;
  wire ce_count_baudrate;
  output ready;
  wire ready;
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire [1:0] _04_;
  wire _05_;
  wire _06_;
  wire [1:0] _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  reg [1:0] etat_cr;
  wire [1:0] etat_sv;
  always @(posedge clk, posedge reset)
    if (reset) etat_cr <= 2'h0;
    else if (_11_) etat_cr <= etat_sv;
  assign _09_ = { _06_, _08_ } != 2'h1;
  assign _10_ = { start, _01_ } != 2'h1;
  assign _11_ = & { _09_, _10_ };
  assign _12_ = | { _02_, _05_, _08_ };
  assign _13_ = | { _01_, _02_, _08_ };
  assign _14_ = | { _01_, _05_, _08_ };
  assign _15_ = | { _01_, _02_, _05_ };
  assign _00_ = start ? 2'h1 : 2'hx;
  assign _01_ = ! etat_cr;
  assign _02_ = etat_cr == 2'h1;
  assign _03_ = count_nb_bits == 4'ha;
  assign _04_ = _03_ ? 2'h0 : 2'h3;
  assign _05_ = etat_cr == 2'h2;
  assign _06_ = count_baudrate == 8'h33;
  assign _07_ = _06_ ? 2'h2 : 2'hx;
  assign _08_ = etat_cr == 2'h3;
  function [0:0] \:203 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \:203  = b[0:0];
      2'b1?:
        \:203  = b[1:1];
      default:
        \:203  = a;
    endcase
  endfunction
  assign ld_ser = \:203 (1'hx, 2'h2, { _02_, _14_ });
  function [0:0] \:223 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \:223  = b[0:0];
      2'b1?:
        \:223  = b[1:1];
      default:
        \:223  = a;
    endcase
  endfunction
  assign ce_count_nb_bits = \:223 (1'hx, 2'h2, { _05_, _13_ });
  function [0:0] \:228 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \:228  = b[0:0];
      2'b1?:
        \:228  = b[1:1];
      default:
        \:228  = a;
    endcase
  endfunction
  assign ce_count_baudrate = \:228 (1'hx, 2'h2, { _08_, _15_ });
  function [0:0] \:233 ;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* parallel_case *)
    casez (s)
      2'b?1:
        \:233  = b[0:0];
      2'b1?:
        \:233  = b[1:1];
      default:
        \:233  = a;
    endcase
  endfunction
  assign raz_count_nb_bits = \:233 (1'hx, 2'h1, { _12_, _01_ });
  function [1:0] \:237 ;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \:237  = b[1:0];
      4'b??1?:
        \:237  = b[3:2];
      4'b?1??:
        \:237  = b[5:4];
      4'b1???:
        \:237  = b[7:6];
      default:
        \:237  = a;
    endcase
  endfunction
  assign etat_sv = \:237 (2'hx, { _07_, _04_, 2'h2, _00_ }, { _08_, _05_, _02_, _01_ });
  assign raz_count_baudrate = ce_count_nb_bits;
  assign raz_ser = 1'h0;
  assign ready = raz_count_nb_bits;
  assign ser = ce_count_nb_bits;
endmodule

module icebreaker(CLK, BTN_N, BTN1, BTN2, BTN3, RX, LED1, LED2, LED3, LED4, TX, P1A1, P1A2, P1A3, P1A4, P1A7, P1A8, P1A9, P1A10, LED_RED_N);
  input CLK;
  wire CLK;
  input BTN_N;
  wire BTN_N;
  input BTN1;
  wire BTN1;
  input BTN2;
  wire BTN2;
  input BTN3;
  wire BTN3;
  input RX;
  wire RX;
  output LED1;
  wire LED1;
  output LED2;
  wire LED2;
  output LED3;
  wire LED3;
  output LED4;
  wire LED4;
  output TX;
  wire TX;
  output P1A1;
  wire P1A1;
  output P1A2;
  wire P1A2;
  output P1A3;
  wire P1A3;
  output P1A4;
  wire P1A4;
  output P1A7;
  wire P1A7;
  output P1A8;
  wire P1A8;
  output P1A9;
  wire P1A9;
  output P1A10;
  wire P1A10;
  output LED_RED_N;
  wire LED_RED_N;
  (* unused_bits = "0" *)
  wire _0_;
  wire ce;
  wire [1:0] comptage;
  wire [7:0] data_to_send;
  wire ld_t;
  wire ready;
  wire reset;
  wire start;
  assign reset = ~ BTN_N;
  compteur_2b_Barch_compteur_2b compteur_2b0 (
    .ce(ce),
    .clk(CLK),
    .count(comptage),
    .raz(reset)
  );
  fsm_icebreaker_Barch_fsm_icebreaker fsm_icebreaker0 (
    .ce(ce),
    .clk(CLK),
    .init(BTN1),
    .ld_t(ld_t),
    .load(BTN2),
    .raz_count(_0_),
    .ready(ready),
    .reset(reset),
    .send(BTN3),
    .start(start)
  );
  rom_Barch_rom_2 rom0 (
    .addr(comptage),
    .data(data_to_send)
  );
  uart_Barch_uart uart0 (
    .clk(CLK),
    .data_to_send(data_to_send),
    .ld_t(ld_t),
    .ready(ready),
    .reset(reset),
    .start(start),
    .tx(TX),
    .tx_test(LED_RED_N)
  );
  assign LED1 = 1'hz;
  assign LED2 = 1'hz;
  assign LED3 = 1'hz;
  assign LED4 = 1'hz;
  assign P1A1 = 1'hz;
  assign P1A10 = 1'hz;
  assign P1A2 = 1'hz;
  assign P1A3 = 1'hz;
  assign P1A4 = 1'hz;
  assign P1A7 = 1'hz;
  assign P1A8 = 1'hz;
  assign P1A9 = 1'hz;
endmodule

module reg_serial_Barch_reg_serial(raz, clk, load, rotate, d_in, tx, tx_test);
  input raz;
  wire raz;
  input clk;
  wire clk;
  input load;
  wire load;
  input rotate;
  wire rotate;
  input [7:0] d_in;
  wire [7:0] d_in;
  output tx;
  wire tx;
  output tx_test;
  wire tx_test;
  wire [10:0] _0_;
  (* unused_bits = "0 1 2" *)
  wire [10:0] _1_;
  wire [10:0] _2_;
  wire _3_;
  wire _4_;
  wire [10:0] interne;
  reg [7:0] _5_;
  always @(posedge clk)
    if (raz) _5_ <= 8'h00;
    else if (_3_) _5_ <= _1_[10:3];
  assign interne[10:3] = _5_;
  reg [2:0] _6_;
  always @(posedge clk)
    if (_4_) _6_ <= 3'h3;
    else if (rotate) _6_ <= _0_[2:0];
  assign { interne[2:1], tx } = _6_;
  assign _3_ = | { rotate, load };
  assign _4_ = | { raz, load };
  assign _0_ = rotate ? _2_ : 11'hxxx;
  assign _1_ = load ? { d_in, 3'h3 } : _0_;
  assign _2_ = { 1'h0, interne[10:1] } | { tx, 10'h000 };
  assign interne[0] = tx;
  assign tx_test = tx;
endmodule

module registre_tampon_Barch_registre_tampon(clk, reset, load, d_in, d_out);
  input clk;
  wire clk;
  input reset;
  wire reset;
  input load;
  wire load;
  input [7:0] d_in;
  wire [7:0] d_in;
  output [7:0] d_out;
  reg [7:0] d_out;
  always @(posedge clk, posedge reset)
    if (reset) d_out <= 8'h00;
    else if (load) d_out <= d_in;
endmodule

module rom_Barch_rom_2(addr, data);
  input [1:0] addr;
  wire [1:0] addr;
  output [7:0] data;
  wire [7:0] data;
  wire [2:0] _0_;
  wire [2:0] _1_;
  assign data[2:0] = addr[1] ? _1_ : _0_;
  assign _0_ = addr[0] ? 3'h2 : 3'h1;
  assign _1_ = addr[0] ? 3'h4 : 3'h3;
  assign data[7:3] = 5'h0c;
endmodule

module uart_Barch_uart(clk, reset, start, ld_t, data_to_send, ready, tx, tx_test);
  input clk;
  wire clk;
  input reset;
  wire reset;
  input start;
  wire start;
  input ld_t;
  wire ld_t;
  input [7:0] data_to_send;
  wire [7:0] data_to_send;
  output ready;
  wire ready;
  output tx;
  wire tx;
  output tx_test;
  wire tx_test;
  wire ce_count_baudrate;
  wire ce_count_nb_bits;
  wire [7:0] count_baudrate;
  wire [3:0] count_nb_bits;
  wire ld_ser;
  wire raz_count_baudrate;
  wire raz_count_nb_bits;
  wire raz_ser;
  wire ser;
  wire [7:0] tamp_out;
  compteur_baudrate_Barch_compteur_baudrate compt_baudrate0 (
    .ce(ce_count_baudrate),
    .clk(clk),
    .count(count_baudrate),
    .raz(raz_count_baudrate)
  );
  compteur_nb_bits_Barch_compteur_nb_bits compt_nb_bits0 (
    .ce(ce_count_nb_bits),
    .clk(clk),
    .count(count_nb_bits),
    .raz(raz_count_nb_bits)
  );
  fsm_serial_Barch_fsm_serial fsm_serial0 (
    .ce_count_baudrate(ce_count_baudrate),
    .ce_count_nb_bits(ce_count_nb_bits),
    .clk(clk),
    .count_baudrate(count_baudrate),
    .count_nb_bits(count_nb_bits),
    .ld_ser(ld_ser),
    .raz_count_baudrate(raz_count_baudrate),
    .raz_count_nb_bits(raz_count_nb_bits),
    .raz_ser(raz_ser),
    .ready(ready),
    .reset(reset),
    .ser(ser),
    .start(start)
  );
  reg_serial_Barch_reg_serial reg_ser (
    .clk(clk),
    .d_in(tamp_out),
    .load(ld_ser),
    .raz(raz_ser),
    .rotate(ser),
    .tx(tx),
    .tx_test(tx_test)
  );
  registre_tampon_Barch_registre_tampon tampon (
    .clk(clk),
    .d_in(data_to_send),
    .d_out(tamp_out),
    .load(ld_t),
    .reset(reset)
  );
endmodule
