/* Generated by Yosys 0.47+135 (git sha1 6f3376cbe, clang++ 18.1.8 -fPIC -O3) */

module cmp_1_bit(but1, but2, clk, reset, led1, led2, led3);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  input but1;
  wire but1;
  input but2;
  wire but2;
  input clk;
  wire clk;
  output led1;
  reg led1;
  output led2;
  reg led2;
  output led3;
  reg led3;
  input reset;
  wire reset;
  assign _06_ = ~ but2;
  assign _07_ = _06_ & but1;
  assign _08_ = but1 == but2;
  assign _09_ = ~ but1;
  assign _10_ = but2 & _09_;
  assign _00_ = _10_ ? 1'h1 : 1'h0;
  assign _01_ = _08_ ? 1'h1 : 1'h0;
  assign _02_ = _08_ ? 1'h0 : _00_;
  assign _03_ = _07_ ? 1'h1 : 1'h0;
  assign _04_ = _07_ ? 1'h0 : _01_;
  assign _05_ = _07_ ? 1'h0 : _02_;
  always @(posedge clk, posedge reset)
    if (reset) led1 <= 1'h0;
    else led1 <= _03_;
  always @(posedge clk, posedge reset)
    if (reset) led2 <= 1'h0;
    else led2 <= _04_;
  always @(posedge clk, posedge reset)
    if (reset) led3 <= 1'h0;
    else led3 <= _05_;
endmodule

module icebreaker(CLK, BTN_N, BTN1, BTN2, BTN3, LED1, LED2, LED3);
  input BTN1;
  wire BTN1;
  input BTN2;
  wire BTN2;
  input BTN3;
  wire BTN3;
  input BTN_N;
  wire BTN_N;
  input CLK;
  wire CLK;
  output LED1;
  wire LED1;
  output LED2;
  wire LED2;
  output LED3;
  wire LED3;
  wire reset;
  assign reset = ~ BTN_N;
  cmp_1_bit cmp_1_bit0 (
    .but1(BTN1),
    .but2(BTN2),
    .clk(CLK),
    .led1(LED1),
    .led2(LED2),
    .led3(LED3),
    .reset(reset)
  );
endmodule
